#!/usr/bin/env bun
/**
 * Provision a TESTER's workspace in the real database: a users row plus the
 * fully-populated demo workspace (master profile, two tailored resumes with
 * revisions and a cover letter, and a pipeline of tracked jobs).
 *
 * This is for people who need to exercise the app rather than use it for real —
 * signing in to an empty account tells you nothing about the flows. The content
 * is the SAME 100% synthetic fixture demo mode uses ("Jane Doe", fake
 * companies): this repo is public and must never carry anyone's real history.
 * Seed a real profile with `bun run seed` instead.
 *
 *   MONGODB_URI=... bun run scripts/seed-workspace.ts --email you@example.com
 *
 * Refuses to touch a row that already has content unless --force is passed, so
 * it can never silently overwrite someone's actual data. Every write goes
 * through the row-scoped repository, so it can only reach the named user's row.
 */
import { buildDemoSeed } from '../src/lib/server/demo/seed';
import { isDemoMode } from '../src/lib/server/config';
import { closeDb } from '../src/lib/server/db/client';
import { createRepository } from '../src/lib/server/db/repository';

function arg(name: string): string | undefined {
	const i = process.argv.indexOf(`--${name}`);
	return i >= 0 ? process.argv[i + 1] : undefined;
}

const email = arg('email')?.trim().toLowerCase();
const force = process.argv.includes('--force');

if (!email) {
	console.error('usage: bun run scripts/seed-workspace.ts --email <address> [--force]');
	process.exit(1);
}

if (isDemoMode()) {
	console.error('Refusing to seed: DEMO_MODE=true writes to the throwaway in-memory store. Unset it.');
	process.exit(1);
}
if (!process.env.MONGODB_URI) {
	console.error('Refusing to seed: MONGODB_URI is not set.');
	process.exit(1);
}

const repo = createRepository(email);

const existingProfile = await repo.profiles.get();
const existingResumes = await repo.resumes.list();
if ((existingProfile || existingResumes.length > 0) && !force) {
	console.error(
		`Refusing to seed: ${email} already has data ` +
			`(profile: ${existingProfile ? 'yes' : 'no'}, resumes: ${existingResumes.length}). ` +
			'Pass --force only if you mean to add demo content on top of it.'
	);
	await closeDb();
	process.exit(1);
}

if (!(await repo.users.findOne({}))) {
	await repo.users.insertOne({ email, createdAt: new Date() });
	console.log(`created users row for ${email}`);
}

const seed = buildDemoSeed(email);

await repo.profiles.upsert(seed.profile, 'Seeded (demo fixture)');

// The seed's resume ids are regenerated by create(); keep the old→new mapping so
// each tracked job still points at the resume it was tailored for.
const resumeIdMap = new Map<string, string>();
for (const r of seed.resumes) {
	const created = await repo.resumes.create(r);
	resumeIdMap.set(r.id, created.id);
}

// Revisions are written explicitly — resumes.update() does NOT snapshot on its
// own (the route calls saveRevision), so without this the version-history panel
// would be empty on a freshly seeded account.
for (const rev of seed.revisions) {
	const resumeId = resumeIdMap.get(rev.resumeId);
	if (resumeId) await repo.resumes.saveRevision(resumeId, rev.doc, rev.label);
}

for (const a of seed.applications) {
	const created = await repo.applications.create({
		url: a.url,
		title: a.title,
		company: a.company,
		status: a.status,
		resumeId: a.resumeId ? (resumeIdMap.get(a.resumeId) ?? null) : null,
		notes: a.notes
	});
	// create() always starts qa empty, so the saved answers go on as a patch.
	if (a.qa.length) await repo.applications.update(created.id, { qa: a.qa });
}

const resumes = await repo.resumes.list();
const applications = await repo.applications.list();
console.log(
	`seeded workspace for ${email}: profile "${seed.profile.basics.name}" · ` +
		`${resumes.length} resumes · ${applications.length} tracked jobs`
);
console.log('Content is synthetic demo data — replace it via /profile/import when testing for real.');

await closeDb();
